# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 15:15
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_postcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='categorie',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='posts.PostCategory'),
        ),
    ]
